package com.google.ai.edge.gallery.ui.theme

import androidx.compose.ui.graphics.Color

// 🌕 LIGHT THEME COLORS
val primaryLight = Color(0xFF7B4FCB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFEBDDFF)
val onPrimaryContainerLight = Color(0xFF2F0059)

val secondaryLight = Color(0xFFB79DF2)
val onSecondaryLight = Color(0xFF261B3D)
val secondaryContainerLight = Color(0xFFE4D9FF)
val onSecondaryContainerLight = Color(0xFF3F2A65)

val tertiaryLight = Color(0xFFDCB1E0)
val onTertiaryLight = Color(0xFF3B003B)
val tertiaryContainerLight = Color(0xFFF8D8FF)
val onTertiaryContainerLight = Color(0xFF540055)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)

val backgroundLight = Color(0xFFFAF7FF)
val onBackgroundLight = Color(0xFF1D1A20)
val surfaceLight = Color(0xFFFAF7FF)
val onSurfaceLight = Color(0xFF1D1A20)
val surfaceVariantLight = Color(0xFFE7DFF1)
val onSurfaceVariantLight = Color(0xFF4E445A)
val outlineLight = Color(0xFF7A7085)
val outlineVariantLight = Color(0xFFD7CEE0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322E38)
val inverseOnSurfaceLight = Color(0xFFF6EDFF)
val inversePrimaryLight = Color(0xFFD3BBFF)
val surfaceDimLight = Color(0xFFE6E0EF)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F0FF)
val surfaceContainerLight = Color(0xFFF0E8FF)
val surfaceContainerHighLight = Color(0xFFEAE2FF)
val surfaceContainerHighestLight = Color(0xFFE4DCFC)


// 🌑 DARK THEME COLORS
val primaryDark = Color(0xFFD3BBFF)
val onPrimaryDark = Color(0xFF3E0075)
val primaryContainerDark = Color(0xFF5A2B91)
val onPrimaryContainerDark = Color(0xFFEBDDFF)

val secondaryDark = Color(0xFFD3BFFF)
val onSecondaryDark = Color(0xFF3B275B)
val secondaryContainerDark = Color(0xFF564176)
val onSecondaryContainerDark = Color(0xFFE4D9FF)

val tertiaryDark = Color(0xFFF0B9FA)
val onTertiaryDark = Color(0xFF490049)
val tertiaryContainerDark = Color(0xFF68186B)
val onTertiaryContainerDark = Color(0xFFF8D8FF)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

val backgroundDark = Color(0xFF140F1C)
val onBackgroundDark = Color(0xFFEDE6F9)
val surfaceDark = Color(0xFF140F1C)
val onSurfaceDark = Color(0xFFEDE6F9)
val surfaceVariantDark = Color(0xFF4E445A)
val onSurfaceVariantDark = Color(0xFFD2C7DD)
val outlineDark = Color(0xFF958CA1)
val outlineVariantDark = Color(0xFF4E445A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEDE6F9)
val inverseOnSurfaceDark = Color(0xFF2E2933)
val inversePrimaryDark = Color(0xFF7B4FCB)
val surfaceDimDark = Color(0xFF1F1A2B)
val surfaceBrightDark = Color(0xFF3A3451)
val surfaceContainerLowestDark = Color(0xFF0E0A13)
val surfaceContainerLowDark = Color(0xFF191322)
val surfaceContainerDark = Color(0xFF211B2C)
val surfaceContainerHighDark = Color(0xFF2A2436)
val surfaceContainerHighestDark = Color(0xFF352F41)
